version: '3'

services:
  order-management:
    container_name: order-management
    image: om
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
